name: Update Blog Posts

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행

jobs:
  update_blog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'Tyranno'
        git config --global user.email 'tofha118@naver.com'

    - name: Pull changes from the remote repository
      run: |
        git pull origin main --rebase

    - name: Push changes
      run: |
        git push https://${{ secrets.GH_PAT }}@github.com/tofha118/velog

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install feedparser gitpython

    - name: Run script
      run: python scripts/update_blog.py
